name: Run Node App

on:
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest

    env:
      ENV: ${{ secrets.ENV }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install
        working-directory: ./delta_gpt_trading_bot_complete  # 👈 tell it where your app.js is

      - name: Run App
        run: node app.js
        working-directory: ./delta_gpt_trading_bot_complete  # 👈 again, tell it the folder
